version: "3.8"

services:
  node:
    image: node:lts-alpine
    container_name: vector-node
    networks:
      - network
    volumes:
      - ../laravel/src:/app
    env_file:
      - .env
    ports:
      - 5173:5173
    working_dir: /app
    entrypoint: sh -c 'npm install && npm run dev'

  nginx:
    depends_on:
      - node

  php:
    volumes:
      - ../laravel/src:/app