version: "3.8"

volumes:
  nginx:
  mysql:
  postgres:
  cache:
  python:

services:
  node:
    image: node:lts-alpine
    container_name: vector-node
    networks:
      - network
    volumes:
      - ../laravel/src:/app
    env_file:
      - ../.env
    ports:
      - 5173:5173
    working_dir: /app
    entrypoint: sh -c 'npm install && npm run dev'

  php:
    volumes:
      - ../laravel/src:/app

  python:
    volumes:
      - ../python/src:/app
      - python:${TORCH_HOME}
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}

  nginx:
    volumes:
      - nginx:/app/public
      - ../laravel/src/public/favicon.ico:/app/public/favicon.ico
      - ../laravel/src/public/hot:/app/public/hot
      - ../laravel/config/nginx/nginx.local.conf.template:/etc/nginx/templates/default.conf.template

  mysql:
    volumes:
      - mysql:/var/lib/mysql

  pgvector:
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    volumes:
      - cache:/data