version: "3.8"

name: "vector-backend"

networks:
  network:

services:
  pgvector:
    image: ankane/pgvector
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - network
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  nginx:
    image: vector-nginx:development
    container_name: vector-nginx
    build:
      context: ../laravel
      target: nginx.${APP_ENV}
    environment:
      - PHP_ENDPOINT=vector-php
    depends_on:
      - php
    networks:
      - network
    ports:
      - 8080:8080

  php:
    image: vector-php:development
    container_name: vector-php
    build:
      context: ../laravel
      target: php.${APP_ENV}
    networks:
      - network
    env_file:
      - ../.env
    depends_on:
      pgvector:
        condition: service_healthy

  python:
    image: vector-python:development
    container_name: vector-python
    build:
      context: ../python
      target: ${APP_ENV}
    env_file:
      - ../.env

  # ---- Redis Single for Local Development ----
  redis:
    platform: linux/amd64
    container_name: vector-redis
    image: redis:7.0
    command: redis-server --requirepass bitnami
    networks:
      - network
