version: "3.8"

services:
  node:
    image: node:lts-alpine
    container_name: vector-node
    networks:
      - network
    volumes:
      - ../laravel/src:/app
    env_file:
      - ../.env
    ports:
      - 5173:5173
    working_dir: /app
    entrypoint: sh -c 'npm install && npm run dev'

  php:
    volumes:
      - ../laravel/src:/app

  python:
    volumes:
      - ../python/src:/app
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}

  nginx:
    volumes:
      - ../laravel/src/public/favicon.ico:/app/public/favicon.ico
      - ../laravel/src/public/hot:/app/public/hot